# Cloud Build configuration for deploying Cloud Functions from repository
# This file supports deploying multiple functions from the LightrunAdapted directory
#
# HOW TO OVERRIDE DEFAULTS (without committing changes):
#   1. In GCP Console: Cloud Build > Triggers > Edit Trigger > Substitution variables
#   2. Add/override any variable (e.g., _FUNCTION_DIR, _ENTRY_POINT, etc.)
#   3. Save and run the trigger
#
# EXAMPLE: To deploy a different function, override these in the trigger:
#   _FUNCTION_DIR: 'LightrunAdapted/nodejs-docs-samples/functions/your-example'
#   _ENTRY_POINT: 'yourFunctionName'
#   _TRIGGER_BUCKET: 'your-bucket-name'
#   _ENV_VARS: 'KEY1=value1,KEY2=value2'

steps:
  # Deploy the Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - '${_FUNCTION_NAME}'                    # Function name (e.g., nadav-gcpjs)
      - '--gen2'
      - '--runtime=${_RUNTIME}'               # Node.js runtime (e.g., nodejs20)
      - '--region=${_REGION}'                 # Region (e.g., europe-west3)
      - '--source=${_FUNCTION_DIR}'           # Source directory path
      - '--entry-point=${_ENTRY_POINT}'       # Function entry point name
      - '--trigger-bucket=${_TRIGGER_BUCKET}' # Storage bucket trigger
      - '--set-env-vars=${_ENV_VARS}'         # Environment variables

# Default substitution variables - ALL can be overridden in Cloud Build trigger settings
# Override these in the trigger to deploy different functions without committing changes
substitutions:
  _FUNCTION_NAME: 'nadav-gcpjs'
  _RUNTIME: 'nodejs20'
  _REGION: 'europe-west3'
  _FUNCTION_DIR: 'LightrunAdapted/nodejs-docs-samples/functions/imagemagick'
  _ENTRY_POINT: 'blurOffensiveImages'
  _TRIGGER_BUCKET: 'lightrun-image-input'
  _ENV_VARS: 'BLURRED_BUCKET_NAME=lightrun-image-output'

# Options - using default (cheapest) machine type
options:
  logging: CLOUD_LOGGING_ONLY
